'''
Solved by: Linda Mansour
Date: 04/03/2024
Language: Python
ID: REVC
Problem: Complementing a Stand of DNA
In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.
The reverse complement of a DNA string s is the string s^c formed by reversing the symbols 
of s then taking the complement of each symbol (e.g., the reverse complement of "GTCA"
is "TGAC").
'''

with open("rosalind_revc.txt") as file:
    s = file.readline().strip()

sc = ""

transcription = {"A": "T",
                "T": "A",
                "C": "G",
                "G": "C",
                "N": "N"}  # holds dictionary of nucleotides & unidentifiable nucleotide


for i in range(len(s)):
    sc += transcription[s[i]]
    
print(sc[::-1])

# Correct Output:
# AGCACCGGACCGGAAGAAAGGAATTAGCCTGCCTTTGAAAGGGCAAGGTATCAGTCGTCCGCGGTCAGCCACGCCTAATTTGCAAATCTAAGACCACCCACCAGAGCCCGCGATAGGACGGAATGACCTGCCGAATCAATGGCGAGAGGCTACCGGCTTTACCAGCAAGCTATGACTGTAGGTCGCAGGAAAGCTGGTCAGCCCTTAACTACAGACGACCGGGACGTATGTACGCAGAGTGCGGCGAGTATAGAATTTCTTGTCCAGAGCGTGGGTTAATGTACCAAGGGTATTTTTCGAAAGTCAGCGATTGAAGCAGCAGTACGATCTGTACCTGCCTTATCATATCGCGTCATCGGGTCCAAAGAATCTGATCTGTCGTATAGACAAGGGACCCGTATCGAAGCATGCTTCATATTGTCAGGAATCTAGTTGAGTGTGTCAAGGCTTGTTAACACGTCACCTTACGTCTATCTCCTATAAGTCACCAGCTACAGCTTCGAGATATGCGATAGGAAGGATCATTTAAGCACGGTGACAAATAATACACCATCGAGCCCTGCGCGGTGTTCTGATCCTAAACGCATCCGTGAGTGACTTTCGTACGGCTCAGTCTTTTCGTCTTTAAGGCAACAGGTCTGGTCAGCGGGATGTTAATCCGGGCACGCCAGTATCTGATGGTACGGAAGGTCAATTACACCGCCGCAGTCCGCGCGCCCGGTGTACGTTCGCGACCGGCACACGCCTCTTGACGTATCGATCCCAAAAAATCCCTGTGCTCTAGGCAGGGCTACACAACTGTTTATTTTCCGAATGCTCGCTTTCGGCTACGTGTAGATCGGTTTCTGGATAAGAAGTGATCTGGGGTAGTCGACATTCAAGTCGCGCGTCACGAC
